export const CREATE_REGISTRATION = 'CREATE_REGISTRATION';
export const GET_TOURNAMENT_TEAM_REQUEST_BY_ID =
  'GET_TOURNAMENT_TEAM_REQUEST_BY_ID';
export const GET_TOURNAMENT_TEAM_REQUEST_BY_USER_ID_AND_TOURNAMENT_ID =
  'GET_TOURNAMENT_TEAM_REQUEST_BY_USER_ID_AND_TOURNAMENT_ID';
