export const GET_TOURNAMENT_MATCH_BY_ID = 'GET_TOURNAMENT_MATCH_BY_ID';
export const CREATE_MATCH = 'CREATE_MATCH';
export const GET_MATCH_BY_USER_ID = 'GET_MATCH_BY_USER_ID';
export const GET_MATCH_BY_ID = 'GET_MATCH_BY_ID';
export const GET_LIST_MATCH_AND_SCORE = 'GET_LIST_MATCH_AND_SCORE';
export const JOIN_MATCH = 'JOIN_MATCH';
export const GET_ALL_MATCH_COMPE_AND_CUSTOM = 'GET_ALL_MATCH_COMPE_AND_CUSTOM';
