export const GET_TOURNAMENT_MATCH_BY_ID = 'GET_TOURNAMENT_MATCH_BY_ID';
export const CREATE_MATCH = 'CREATE_MATCH';
export const GET_MATCH_BY_USER_ID = 'GET_MATCH_BY_USER_ID';
export const GET_MATCH_BY_ID = 'GET_MATCH_BY_ID';
