export const GET_TOURNAMENT_BY_ID = 'GET_TOURNAMENT_BY_ID';
export const GET_TOURNAMENT_MATCH_BY_ID = 'GET_TOURNAMENT_MATCH_BY_ID';
export const GET_ALL_TOURNAMENTS = 'GET_ALL_TOURNAMENTS';
export const CREATE_TOURNAMENT = 'CREATE_TOURNAMENT';
