export const GET_TOURNAMENT_BY_ID = 'GET_TOURNAMENT_BY_ID';
export const GET_TOURNAMENT_MATCH_BY_ID = 'GET_TOURNAMENT_MATCH_BY_ID';
export const GET_ALL_TOURNAMENTS = 'GET_ALL_TOURNAMENTS';
export const CREATE_TOURNAMENT = 'CREATE_TOURNAMENT';
export const GET_TOURNAMENT_BY_USER_ID_AND_TOURNAMENT_ID =
  'GET_TOURNAMENT_BY_USER_ID_AND_TOURNAMENT_ID';
export const GET_ALL_TOURNAMENTS_PLAYER = 'GET_ALL_TOURNAMENTS_PLAYER';
export const GET_RULE_OF_AWARD = 'GET_RULE_OF_AWARD';
