export const GET_ALL_BILLS_BY_TOURNAMENT_ID = 'GET_ALL_BILLS_BY_TOURNAMENT_ID';
export const GET_ALL_BILLS = 'GET_ALL_BILLS';
export const GET_PAYMENT_URL = 'GET_PAYMENT_URL';
export const CHECK_PAYMENT = 'CHECK_PAYMENT';
