export const FETCH_ALL_USERS = 'FETCH_ALL_USERS';
export const FETCH_REFEREES = 'FETCH_REFEREES';
export const FETCH_ME = 'FETCH_ME';
export const FETCH_SPONSOR = 'FETCH_SPONSOR';
export const FETCH_PLAYER = 'FETCH_PLAYER';
export const FETCH_ALL_ORGANIZERS = 'FETCH_ALL_ORGANIZERS';
export const FETCH_ALL_STAFFS = 'FETCH_ALL_STAFFS';
